# Generated by Django 4.1 on 2022-10-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_kategori_movie_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videolar/'),
        ),
    ]
